{% set version = "3.0.1" %}
{% set stage = "" %}

package:
  name: dunovo
  version: "{{ version }}"

source:
  fn: v2.15.tar.gz
  url: https://github.com/galaxyproject/dunovo/archive/v2.15.tar.gz
  sha256: 1cf02bcc37cc641a20bdf5e20c2b3b98d4dccd43b1182830cb1a9e7d173d1a78

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  run:
    - bowtie <1.2.0|>=1.3.0
test:
  commands:
    - 'true'

about:
  home: https://github.com/galaxyproject/dunovo
  license: GPL2
  license_file: COPYING
  summary: "Du Novo: A pipeline for processing duplex sequencing data."
