{% set version = "3.0.1" %}
{% set stage = "" %}

package:
  name: dunovo
  version: "{{ version }}"

source:
  fn: v{{ version }}{{ stage }}.tar.gz
  url: https://github.com/galaxyproject/dunovo/archive/v{{ version }}{{ stage }}.tar.gz
  sha256: 0f399a424503d4ea1587eafd0874335997695590039b2513a34da79a8eed686f

build:
  number: 0
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}

  run:

test:
  commands:
    - 'true'

about:
  home: https://github.com/galaxyproject/dunovo
  license: GPL2
  license_file: COPYING
  summary: "Du Novo: A pipeline for processing duplex sequencing data."
